name: pet_adoption_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  flutter_bloc: ^8.1.3
  dio: ^4.0.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.8
  flutter_dialogs: ^3.0.0
  confetti: ^0.7.0
  photo_view: ^0.14.0
  flutter_svg: any
  google_fonts: ^5.1.0
  oauth2: ^2.0.2
  animations: ^2.0.7
  font_awesome_flutter: ^10.4.0
  awesome_dialog: ^2.2.1
  open_peeps: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
